project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://mtanviruzzaman.github.io/nature/
  repo-url: https://github.com/mtanviruzzaman/nature
  title: "The Nature Curriculum"
  navbar:
    right:
      - icon: github
        href: https://github.com/mtanviruzzaman/nature
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

comments:
  giscus:
    repo: mtanviruzzaman/nature
    category: Announcements
    mapping: pathname
    reactions-enabled: true

