project:
  type: website
  resources:
    - "google5d421e78becd6e78.html"
website:
  description: "A blog built with Quarto"
  site-url: https://mtanviruzzaman.github.io/nature/
  repo-url: https://github.com/mtanviruzzaman/nature
  title: "Reading Nature"
  navbar:
    title: false
    collapse: false
    left:
      - icon: house
        href: index.qmd
        text: "&nbsp;"
        aria-label: "Home"
    right:
      - icon: github
        href: https://github.com/mtanviruzzaman/nature
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

comments:
  giscus:
    repo: mtanviruzzaman/nature
    category: Announcements
    mapping: pathname
    reactions-enabled: true

