---
title: "Good habits, bad habits"
author: "Mohammad Tanviruzzaman"
date: "2026-10-09"
categories: [life]
---

> A habit is a learned association between a recurring context cue and a response, strengthened through repetition and often supported by rewards. Arranging the environment to reduce friction makes the response easier to repeat—metaphorically lowering its “activation energy.” As the association strengthens, the cue can trigger the response with little deliberation or mental effort. The response can persist even when the original reward is no longer valued, although conscious goals can still intervene.

## Sources
* Good Habits, Bad Habits by Wendy Wood
* [Goals and Habits in the Brain](https://www.gatsby.ucl.ac.uk/~dayan/papers/dolandayan2013.pdf)
* [Habits Without Values](https://kevinjmiller.org/wp-content/uploads/2019/01/millershenhavludvig_psychrev_inpress.pdf)
* [Rethinking Approach and Avoidance in Achievement Contexts:
The Perspective of Dynamical Systems](https://www.researchgate.net/publication/290818619_Rethinking_Approach_and_Avoidance_in_Achievement_Contexts_The_Perspective_of_Dynamical_Systems)
* [Habit scorecard](https://jamesclear.com/habits-scorecard)
* [Personalized script eliciation for improving evening sleep hygine habits](https://pmc.ncbi.nlm.nih.gov/articles/PMC9815428/pdf/RHPB_11_2162904.pdf)