---
title: "Hidden history in Physics textbooks"
author: "Mohammad Tanviruzzaman"
date: "2026-09-04"
categories: [physics]
---

**tl;dr** 

> Many introductory physics textbooks echo the subject's historical arc---from mechanics to fields to quantum theory.

In [The Evolution of Physics](https://archive.org/details/B-001-002-263/mode/2up), Einstein and Infeld argue that Physics has evolved in three sequential phases:

<details>
<summary>Mechanical view</summary>

"*In mechanics the future path of a moving body can be predicted and its past disclosed if its present condition and the forces acting upon it are known. Thus, for example, the future paths of all planets can be foreseen. The active forces are Newton's gravitational forces depending on the distance alone. The great results of classical mechanics suggest that the mechanical view can be consistently applied to all branches of physics, that all phenomena can be explained by the action of forces representing either attraction or repulsion, depending only upon distance and acting between unchangeable particles.*

*In the kinetic theory of matter we see how this view, arising from mechanical problems, embraces the phenomena of heat and how it leads to a successful picture of the structure of matter.*

*In the old theories of electric fluids, in the corpuscular and wave properties of light, we witness the further attempts to apply the mechanical view. But in the realm of electric and optical phenomena we meet grave difficulties in the application.*

*A moving charge acts upon a magnetic needle. But the force, instead of depending only upon distance, depends also upon the velocity of the charge. The force neither repels nor attracts but acts perpendicular to the line connecting the needle and the charge.*

*In optics we have to decide in favor of the wave theory against the corpuscular theory of light. Waves spreading in a medium consisting of particles, with mechanical forces acting between them, are certainly a mechanical concept. But what is the medium through which light spreads and what are its mechanical properties? There is no hope of reducing the optical phenomena to the mechanical ones before this question is answered. But the difficulties in solving this problem are so great that we have to give it up and thus give up the mechanical view as well.*"

</details>

<details>
<summary>Field view</summary>

"*A new concept appears in physics, the most important invention since Newton's time: the field. It needed great scientific imagination to realize that it is not the charges nor the particles but the field in the space between the charges and the particles which is essential for the description of physical phenomenon. The field concept proves most successful and leads to the formulation of Maxwell's equations describing the structure of the electromagnetic field and governing the electric as well as the optical phenomena.*

*The theory of relativity arises from the field problems. The contradictions and inconsistencies of the old theories force us to ascribe new properties to the time-space continuum, to the scene of all events in our physical world.*

*The relativity theory develops in two steps. The first step leads to what is known as the special theory of relativity, applied only to inertial co-ordinate systems, that is, to systems in which law of inertia, as formulated by Newton, is valid. The special theory of relativity is based on two fundamental assumptions: physical laws are the same in all co-ordinate systems moving uniformly, relative to each other; the velocity of light always has the same value. From these assumptions, fully confirmed by experiment, the properties of moving rods and clocks, their changes in length and rhythm depending on velocity, are deduced. The theory of relativity changes the laws of mechanics. The old laws are invalid if the velocity of the moving particle approaches that of light. The new laws for a moving body as reformulated by the relativity theory are splendidly confirmed by experiment. A further consequence of the (special) theory of relativity is the connection between mass and energy. Mass is energy and energy has mass. The two conservation laws of mass and energy are combined by the relativity theory into one, the conservation law of mass-energy.*

*The general theory of relativity gives a still deeper analysis of the time-space continuum. The validity of the theory is no longer restricted to inertial co-ordinate systems. The theory attacks the problem of gravitation and formulates new structure laws for the gravitational field. It forces us to analyze the role played by geometry in the description of the physical world. It regards the fact that gravitational and inertial mass are equal, as essential and not merely accidental, as in classical mechanics. The experimental consequences of the general relativity theory differ only slightly from those classical mechanics. They stand the test of experiment well wherever comparison is possible. But the strength of the theory lies in its inner consistency and the simplicity of its fundamental assumptions.*

*The theory of relativity stresses the importance of the field concept in physics. But we have not yet succeeded in formulating a pure field physics. For the present we must still assume the existence of both: field and matter.*"

</details>

<details>
<summary>Quantum view</summary>

"*Again the rich variety of facts in the realm of atomic phenomena forces us to invent new physical concepts. Matter has a granular structure; it is composed of elementary particles, the elementary quanta of matter. Thus, the electric charge has a granular structure and---most important from the point of view of the quantam theory---so has energy. Photons are the energy quanta of which light is composed.*

*Is light a wave or a shower of photons? Is a beam of electrons a shower of elementary particles or a wave? These fundamental questions are forced upon physics by experiment. In seeking to answer them we have to abandon the description of atomic events as happenings in space and time, we have to retreat still further from the old mechanical view. Quantum physics formulates laws governing crowds and not individuals. Not properties but probabilities are described, not laws disclosing the future of systems are formulated, but laws governing the changes in time of the probabilities and relating to great congregations of individuals.*"

</details>

The chapters in a typical undergrad Physics textbook follow the same sequence as the phases. For example,

1. University Physics (14th edition) by Young and Freedman: 
- _Mechanical View_: Chapter 01 (Units, physical quantities, and vectors) --- Chapter 20 (The second law of thermodynamics) 
- _Field View_: Chapter 21 (Electric charge and electric field) --- Chapter 37 (Relativity)
- _Quanta View_: Chapter 38 (Photons: Light waves behaving as particles) --- Chapter 44 (Particle physics and cosmology)

2. Physics for Scientists and Engineers (3rd edition) by Knight:
- _Mechanical View_: Chapter 01 (Concepts of Motion) --- Chapter 24 (Optical Instruments) 
- _Field View_: Chapter 25 (Electricity and magnetism) --- Chapter 36 (Relativity)
- _Quanta View_: Chapter 37 (The foundations of modern physics) --- Chapter 42 (Nuclear physics)

3. Physics (3rd edition) by Halliday and Resnick:
- _Mechanical View_: Chapter 01 (Measurement) --- Chapter 25 (Entropy and the second law of thermodynamics) 
- _Field View_: Chapter 26 (Charge and matter) --- Chapter 48 (Polarization)
- _Quanta View_: Chapter 49 (Light and quantum physics) --- Chapter 50 (Waves and particles)